[package]
name = "Part2"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.9.0"

[[bench]]
name = "my_benchmark"
harness = false